api = "0.2"

[buildpack]
id = "instana.gcp.cloudrun"
version = "1.0.0-SNAPSHOT"
name = "Instana Google Cloud Run Buildpack"
homepage = "https://github.com/instana/instana-buildpacks"

[[stacks]]
id = "google"
